#!/bin/sh
#
#     |\      _,,,---,,_
#     /,`.-'`'    -.  ;-;;,_
#    |,4-  ) )-,_. ,\ (  `'-'
#   '---''(_/--'  `-'\_)
#
# river config file

################
# startup apps #
################
kanshi &
waybar &
mako &
gammastep -c ~/.config/gammastep/gammastep.ini &
fcitx5 &

###########
# general #
###########

# background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75

# layout generator
riverctl default-layout rivertile
riverctl attach-mode bottom
rivertile -view-padding 4 -outer-padding 4 -main-ratio 0.55 -main-location left &

# focus follows cursor
riverctl focus-follows-cursor always

###########
# hotkeys #
###########

# programs
riverctl map normal Super Return spawn alacritty
riverctl map normal Super F spawn firefox
riverctl map normal Super E spawn thunar
riverctl map normal Super+Shift C spawn qalculate-gtk
riverctl map normal Super+Shift L spawn swaylock
riverctl map normal Super R spawn ~/.config/rofi/launchers/type-1/launcher.sh
riverctl map normal Super+Shift E spawn ~/.config/rofi/powermenu/type-1/powermenu.sh

# laptop shortcuts
for mode in normal locked
do
    # audio
    riverctl map $mode None XF86AudioRaiseVolume spawn 'pactl -- set-sink-volume 0 +5%'
    riverctl map $mode None XF86AudioLowerVolume spawn 'pactl -- set-sink-volume 0 -5%'
    riverctl map $mode None XF86AudioMute spawn 'pactl -- set-sink-mute @DEFAULT_SINK@ toggle'
    riverctl map $mode None XF86AudioMicMute spawn 'pactl set-source-mute @DEFAULT_SOURCE@ toggle'

    # screen backlight
    riverctl map $mode None XF86MonBrightnessUp spawn 'brightnessctl set 5%+'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

#########
# input #
#########

# keyboard
riverctl keyboard-layout it
riverctl set-repeat 50 300

# mouse
riverctl input "pointer-5426-138-Razer_Razer_Viper_Mini" accel-profile flat

# touchpad
riverctl input "pointer-1267-12737-ASUE120C:00_04F3:31C1_Touchpad" tap enabled
riverctl input "pointer-1267-12737-ASUE120C:00_04F3:31C1_Touchpad" middle-emulation enabled
riverctl input "pointer-1267-12737-ASUE120C:00_04F3:31C1_Touchpad" natural-scroll enabled
riverctl input "pointer-1267-12737-ASUE120C:00_04F3:31C1_Touchpad" tap-button-map left-right-middle
riverctl input "pointer-1267-12737-ASUE120C:00_04F3:31C1_Touchpad" scroll-method two-finger
riverctl input "pointer-1267-12737-ASUE120C:00_04F3:31C1_Touchpad" accel-profile adaptive

#####################
# window management #
#####################

# kill focused window
riverctl map normal Super Q close

# change focus
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# move focused window
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# resize focused window
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# resize floating windows with mouse
riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

# toggle float / fullscreen
riverctl map normal Super Space toggle-float
riverctl map normal Super+Shift F toggle-fullscreen

# change layout orientation
riverctl map normal Super Up send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left send-layout-cmd rivertile "main-location left"

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # change workspace
    riverctl map normal Super $i set-focused-tags $tags

    # move a window to specified workspace
    riverctl map normal Super+Shift $i set-view-tags $tags

    # toggle focus of a certain tag
    riverctl map normal Super+Control $i toggle-focused-tags $tags
done

# focus all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 toggle-focused-tags $all_tags

# force floating mode
riverctl rule-add float -app-id "qalculate-gtk"
riverctl rule-add float -app-id "thunar"
riverctl rule-add float -app-id "lutris"
riverctl rule-add float -class "steam"
riverctl rule-add float -class "dolphin-emu"
riverctl rule-add float -class "YouTube Music"
